<?php
    // within a view script
    $form = $this->form;
    $form->prepare();

    // Assuming the "contact/process" route exists...
    $form->setAttribute('action', $this->BasePath() . '/user-update');
    $form->setAttribute('id', 'updateForm');

    // Set the method attribute for the form
    $form->setAttribute('method', 'post');

    // Get the form label plugin
    $formLabel = $this->plugin('formLabel');


?>
      <!--INICIO Header-menu -->
            <nav id="menuHeader">
            <div class="container">
                <div class="row">
                    <div class=" col-md-offset-1 col-md-10   col-xs-offset-1 col-xs-10">
                     <ul id="navegacion">
                        <li><a href="<?php echo $this->url('website-main'); ?>">HOME</a></li>
                         <li><a href="<?php echo $this->url('store-salads'); ?>">CREA TU ENSALADA</a></li>
                         <li><a href="<?php echo $this->url('store-combos'); ?>">ARMA TU COMBO</a></li>
                         <li><a href="<?php echo $this->url('store-products'); ?>">MENÚ DE PRODUCTOS</a></li>
                         <li><a href="<?php echo $this->url('store-car'); ?>">CARRITO DE COMPRAS</a></li>
                   </ul>
 <a href="<?php echo $this->url('store-car'); ?>"> <img src="<?php echo $this->BasePath(); ?>/img/compras.png" alt="carrito de compras" id="logoCarrito" class="zoom"></a>
                     </div>
                </div>
            </div>
     </nav>
       <div class="headerMobile">
            <a class="btn-menu"><span class="glyphicon glyphicon-align-justify"></span></a>
            <ul id="redesMobile">
             <li><a href="#"><span class="icon-facebook"></span></a></li>
              <li><a href="#"><span class="icon-twitter"></span></a></li>
              <li><a href="#"><span class="icon-youtube"></span></a></li>
              <li><a href="#"><span class="icon-instagram"></span></a></li>
             </ul>
           <nav class="menuMobile">
             <ul>
                <li><a href="<?php echo $this->url('website-main'); ?>"><span class="glyphicon glyphicon-home"></span>HOME</a></li>
                <li><a href="<?php echo $this->url('store-salads'); ?>"><span class="icon-leaf"></span>CREA TU ENSALADA</a></li>
                 <li><a href="<?php echo $this->url('store-combos'); ?>"><span class="glyphicon glyphicon-cutlery"></span>ARMA TU COMBO</a></li>
                <li><a href="<?php echo $this->url('store-products'); ?>"><span class="glyphicon glyphicon-cutlery"></span>MENÚ DE PRODUCTOS</a></li>
                <li><a href="<?php echo $this->url('store-car'); ?>"><span class="icon-cart"></span>CARRITO DE COMPRAS</a></li> 

            </ul>
         </nav>
     </div>
    <!--FIN Header-menu -->
     <div class="container">
            <div class="row">
                <div class=" col-md-offset-1 col-md-10">
                    <div class="row">
                 <div class="col-md-12 col-xs-12">
                       <h2 class="creaEn2">Mis Datos</h2>
                       <div>
              <hr>
            </div>
               <?php echo $this->form()->openTag($form); ?>
                    <div class="col-xs-12 col-md-6 padding">
                        <div class="form-group">
                            <label for="nombre">Nombre:</label>
                            <?php 
                                $nombre = $form->get('nombre');
                                echo $this->formInput($nombre);
                                echo $this->formElementErrors($nombre);
                            ?>
                        </div>
                        <div class="form-group">
                            <label for="telefono">Telefono:</label>
                            <?php 
                                $telefono = $form->get('telefono');
                                echo $this->formInput($telefono);
                                echo $this->formElementErrors($telefono);
                            ?>
                        </div>
                    </div>    
                    <div class="col-xs-12 col-md-6 padding">
                        <div class="form-group">
                            <label for="direccion">Dirección:</label>
                            <?php 
                                $direccion = $form->get('direccion');
                                echo $this->formInput($direccion);
                                echo $this->formElementErrors($direccion);
                            ?>
                        </div>
                         <div class="form-group">
                            <button type="submit" class="btn btn-success btn-block" id="actualizarUser">Actualizar información</button>
                    </div>
                    </div>   
                   
                <?php echo $this->form()->closeTag(); ?>
                <?php if ($this->flashMessenger()->hasMessages()){ ?>
                    <div id="message_register" class="alert alert-info fade in col-md-12 text-center">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong><?php echo $this->flashMessenger()->getMessages()[0]; ?></strong>
                    </div>
                <?php } ?>  
                 </div>
             </div>
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <h2 class="creaEn2">Mis Ensaladas</h2> 
                    <div>
              <hr>
            </div>
                      
                  <table class="table  table-bordered  table-striped text-center" >
                    <thead>
                      <tr>
                        <th class="text-center">Nombre</th>
                        <th class="text-center">Cantidad</th>
                        <th class="text-center">Opciones</th>

                      </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->ensaladas as $ensalada) {?>
                            <tr id="<?php echo base64_encode(base64_encode($ensalada['id'])); ?>">
                                <td><?php echo $ensalada['nombre'] ?></td>
                                <td>
                                     <div class="form-group">
                                         <select class="form-control" id="cant">
                                             <option>1</option>
                                             <option>2</option>
                                             <option>3</option>
                                             <option>4</option>
                                             <option>5</option>
                                             <option>6</option>
                                             <option>7</option>
                                             <option>8</option>
                                             <option>9</option>
                                             <option>10</option>
                                        </select>
                                    </div>
                                </td>
                                <td>
                                    <button type="button" class="deleteUserSalad btn btn-danger"><span class="glyphicon glyphicon-trash"></span></button>
                                    <button type="button" class="addSaladToCar btn btn-success"><span class="glyphicon glyphicon-shopping-cart"></span></button>
                                </td>
                            </tr>
                         <?php } ?>
                    </tbody>
              </table>
                
                </div>
                 <div class="col-md-12 col-xs-12">
                    <h2 class="creaEn2">Historial de compras</h2>  
                    <div>
                        <hr>
                    </div>      
                  <table class="table  table-bordered  table-striped text-center" id="hist" >
                    <thead>
                      <tr>
                        <th class="text-center">Producto</th>
                        <th class="text-center">Fecha</th>
                      </tr>
                    </thead>
                    <tbody>
                         <tr>
                            <td>
                                 Dominguera 
                            </td>
                           <td>
                                 15-03-216
                            </td>
                         </tr>
                           <tr>
                            <td>
                                 Hamgurguesa
                            </td>
                           <td>
                                 17-03-216
                            </td>
                         </tr>
    
                    </tbody>
              </table>
                
                </div>
            </div>
                </div>
            </div>
             
   </div>
